# Generated by Django 3.2 on 2024-09-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rptlrmf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('view_num', models.IntegerField()),
            ],
        ),
    ]
